spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    driver-class-name: org.postgresql.Driver
    username: testuser
    password: "test"
#
#spring:
#  datasource:
#    own:
#      username: ${CONTAINER.USERNAME}
#      password: ${CONTAINER.PASSWORD}
#      url: ${CONTAINER.URL}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml